name: Build & Publish ECR

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Run build
        run: npm run build
        working-directory: ./src
      
      # - name: Run Tests
      #   run: npm run build

      # - name: Run Lint
      #   run: npm run build

      - name: Build Docker image
        run: docker build -t 'ecs-api:${{ github.sha }}' .
        working-directory: ./src
      
      - name: Setup Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ecs-api:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image to ECR
        run: 
          |
            echo "Push to ECR"
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform validate
        run: terraform validate
        working-directory: ./infra
      
      # - name: Terraform Plan
      #   run: terraform plan
      #   working-directory: ./terraform